### ISSUE TITLE
Keep the arcade guns

### ISSUE THREAD

**Issue by Koud-Wind** [Paneedah/Modern-Warfare-Cubed#22]
## Is your feature request related to a problem? Please describe

***Their existence can make the module more playable, such as fatman, gpca1, pgm_ hecate_ Ii, not hk_ g95,c8_ Sfw those semi-finished firearms*** 

## Describe the solution you'd like

***Keep the guns of the war server***

## Describe alternatives you've considered

***N/A***

## Additional context

***N/A***

**Comment by JustDesoroxxx** [comment]
Arcade guns will come back when the sister mod (Modern Warfare Cubed: Arcade) is created and artist create them
